data_path: "sdvae-official latents path"
results_dir: "dit-updates/dit-rfm-xl-2-256__imagenet2012__sdvae-official"
vae: sdvae-official
model: DiT-XL/2
image_size: 256
num_classes: 1000
epochs: 100
global_batch_size: 512
global_seed: 0
num_workers: 8
log_every: 100
ckpt_every: 50000
last_ckpt_every: 10000
sample_every: 5
cfg_scale: 4.0
num_sampling_steps: 100

objective: rfm
rfm:
  time_shift: 3.0
  time_emb_scale: 6.28
  num_val_steps: 100
  base_sampler: "logit-normal"
  sigma_time_dist: 1.0
  pred_mode: "flow"
